.base_job_template: &base_job_template
  image: rubydev/ruby-chrome:2.7
  tags:
    - docker
  variables:
    RAILS_ENV: "test"
    BUNDLE_CACHE: "vendor/bundle"
  cache:
    untracked: true
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - vendor/bundle
      - node_modules

.test_job_template: &test_job_template
  <<: *base_job_template
  services:
    - postgres:12.1
  stage: test
  before_script:
    - "echo 'gem: --no-rdoc --no-ri' > ~/.gemrc"
    - gem install bundler
    - bundle config set path 'vendor/bundle'
    - bundle install -j4
    - cp config/database.yml.sample.ci config/database.yml

stages:
  - test

rubocop:
  <<: *test_job_template
  script:
    - bundle exec rubocop

# 以下は、slimlint を使う場合です。
# 試してませんので誤りがある場合は各自で試してください。
# slimlint:
#   <<: *test_job_template
#   script:
#     - bundle exec slimlint

# TODO: rspec 導入後に最後に `- bundle exec rspec` を追加してください。
rspec:
  <<: *test_job_template
  script:
    - yarn install
    - bundle exec rails db:setup
    - bundle exec rspec
