.base_job_template: &base_job_definition
  image: circleci/ruby:2.7-buster-node-browsers
  image: circleci/ruby:2.7.0-buster-node-browsers
  tags:
    - docker
  variables:
    RAILS_ENV: "test"
    BUNDLE_CACHE: "vendor/bundle"
  cache:
    untracked: true
    key: "$CI_COMMIT_REF_SLUG"
    key:
      files:
        - Gemfile.lock
        - package.json
      prefix: "$CI_COMMIT_REF_SLUG"
    paths:
      - vendor/bundle
      - node_modules

.test_job_template: &test_job_template
  <<: *base_job_definition
  services:
    - postgres:12.1
  stage: test
  before_script:
    - bundle install --path vendor/bundle
    - cp config/database.yml.sample.ci config/database.yml

stages:
  - test

rubocop:
  <<: *test_job_template
  script: bundle exec rubocop
  allow_failure: true

rspec:
  <<: *test_job_template
  script:
    - yarn install
    - bundle exec rails db:setup
    - bundle exec rspec
